### ISSUE TITLE
Warnings in logs

### ISSUE THREAD

**Issue by rudizl** [d-sergienko/ha-tesy#2]
A few warnings have raised in logs. I'm posting them here:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:234
First occurred: December 16, 2024 at 22:45:27 (1 occurrences)
Last logged: December 16, 2024 at 22:45:27

Detected code that calls async_forward_entry_setup for integration tesy with title: Tesy and entry_id: 01JF7A02K5C2N5ZC8KDFMN2G25, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1655
First occurred: December 16, 2024 at 22:45:27 (1 occurrences)
Last logged: December 16, 2024 at 22:45:27

Entity None (<class 'custom_components.tesy.water_heater.TesyWaterHeater'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <WaterHeaterEntityFeature.TARGET_TEMPERATURE|OPERATION_MODE|AWAY_MODE: 7>, please report it to the author of the 'tesy' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: December 16, 2024 at 22:45:23 (3 occurrences)
Last logged: December 16, 2024 at 22:45:27

Detected that custom integration 'tesy' calls async_forward_entry_setup for integration, tesy with title: Tesy and entry_id: 01JF7A02K5C2N5ZC8KDFMN2G25, which is deprecated, await async_forward_entry_setups instead at custom_components/tesy/__init__.py, line 38: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please report it to the author of the 'tesy' custom integration
Detected that custom integration 'tesy' registers an entity service with a non entity service schema at custom_components/tesy/water_heater.py, line 90: platform.async_register_entity_service(. This will stop working in Home Assistant 2025.9, please report it to the author of the 'tesy' custom integration
Detected that custom integration 'tesy' registers an entity service with a non entity service schema at custom_components/tesy/water_heater.py, line 93: platform.async_register_entity_service(. This will stop working in Home Assistant 2025.9, please report it to the author of the 'tesy' custom integration

Logger: homeassistant.const
Source: helpers/deprecation.py:222
First occurred: December 16, 2024 at 22:45:27 (1 occurrences)
Last logged: December 16, 2024 at 22:45:27

TEMP_CELSIUS was used from tesy, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'tesy' custom integration

Logger: homeassistant.components.water_heater
Source: helpers/deprecation.py:222
integration: Water heater (documentation, issues)
First occurred: December 16, 2024 at 22:45:27 (6 occurrences)
Last logged: December 16, 2024 at 22:45:27

SUPPORT_OPERATION_MODE was used from tesy, this is a deprecated constant which will be removed in HA Core 2025.1. Use WaterHeaterEntityFeature.OPERATION_MODE instead, please report it to the author of the 'tesy' custom integration
SUPPORT_TARGET_TEMPERATURE was used from tesy, this is a deprecated constant which will be removed in HA Core 2025.1. Use WaterHeaterEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'tesy' custom integration
SUPPORT_AWAY_MODE was used from tesy, this is a deprecated constant which will be removed in HA Core 2025.1. Use WaterHeaterEntityFeature.AWAY_MODE instead, please report it to the author of the 'tesy' custom integration

**Comment by d-sergienko** [comment]
Thanks for your feedback, Radoslav.

I think I will not spend time to fix this, as the right way is to merge my code with parallel project, which is in HACS already.

**Comment by rudizl** [comment]
Ok, thank you :)
